<?php
/**
 * Created by IntelliJ IDEA.
 * User: Ror
 * Date: 19.04.2015
 * Time: 15:16
 */

/**
 * <pre>
 * Project autoload function.
 * Class with name 'Page' must be in modules/page/Page.php file.
 * If class have name PageService it must be in modules/page/Service.php file
 * If class have name Page_Admin_Includes, it must be in modules/page/Admin/Includes.php file
 *
 * If class have name Page, but there is no modules/page/Page.php file, function will try
 * to search it in modules/Page.php. If there is no that file, exception will be thrown on require_once construction
 *
 * Also, this function used for ORM persistance class loading
 * If no one of previous condition was executted, it will try to search your file in
 * ORM::getPersistExtendedObjectsFolder().$class.".php" for extended persistance classes, and
 * ORM::getPersistObjectsFolder().$class.".php" for autogenerated classes
 *
 * </pre>
 * @param string $class
 */
function forwebAutoload($class) {
    $file = $class.'.php';
    if(is_file(Core::MODULES_FOLDER.strtolower($class).'/'.$file)) {
        require_once Core::MODULES_FOLDER.strtolower($class).'/'.$file;
        return;
    }
    if(is_file(Core::MODULES_FOLDER.$file)) {
        require_once Core::MODULES_FOLDER.$file;
        return;
    }
    $parts = preg_split("/(?<=[a-z])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])|([_]{1,})/", $class);

    $folder = Core::MODULES_FOLDER;
    foreach($parts as $part) {
        $folder .= $part.'/';
        $fullPath = $folder.$file;
        if(is_file($fullPath)) {
            require_once $fullPath;
            return;
        }
    }
}