<?php

/**
 * Class ORM
 * Main class for work with objective datasource model.
 */
class ORM{
    const EXTEND = "Ext";
    /**
     * links collection to tables
     * ORM_Table[]
     */
    protected static $registeredTables;

    /**
     * get folder, where serialized tables stored
     * @return string
     */
    public static function getTablesFolder(){
        return "cache/ORM/Tables/";
    }

    public static function getPersistObjectsFolder(){
        return "modules/orm/autogenerated/";
    }

    public static function getPersistExtendedObjectsFolder(){
        return ORM::getPersistObjectsFolder()."extend/";
    }

    /**
     * Load binded data for object. Use on lazy load
     * @param $tableName string
     * @param $keyValue
     * @param $leftKey
     * @param $rightKey
     * @param $type
     * @return OrmPersistenceBase|OrmPersistenceBase[]
     */
    public static function loadBinded($tableName, $keyValue, $leftKey, $rightKey, $type) {
        $mainTable = ORM::getTable($tableName);
        $filter = new OrmQueryFilter($mainTable->getName(), $rightKey, OrmQueryFilter::TYPE_EQUAL);
        $filter->setValue($keyValue);
        $filter->setActive(true);
        $one = $type == OrmTable::ONE_TO_ONE || $type == OrmTable::MANY_TO_ONE;
        return OrmUtils::load($mainTable, $one, array($filter), null, null);
    }


    /**
     * Load data from persistence storage
     * @param string $tableName - name of main table for object
     * @param string $tail - 'where', 'order', etc
     * @param boolean $binds - inlude all binded data
     * @param boolean $one - expected one object or null
     * @return mixed
     */
    public static function load($tableName, $one, $filters, $sorters, $pager) {
        $mainTable = ORM::getTable($tableName);
        return OrmUtils::load($mainTable, $one, $filters, $sorters, $pager);
    }

    /**
     * Save one multy leveled data array. Structure element - OrmPersistenceBase class object
     *
     * @param OrmTable $mainTable
     * @param $object
     */
    public static function saveArray (OrmTable $mainTable, $object) {
        OrmUtils::saveArray($mainTable, $object);
    }

    /**
     * Save or update OrmPersistenceBase object
     */
    public static function saveData (OrmTable $table, OrmPersistenceBaseImpl $object) {
        OrmUtils::saveData($table, $object);
    }

    /**
     * Delete object from data base
     */
    public static function delete(OrmTable $table, OrmPersistenceBaseImpl $object) {
        return OrmUtils::delete($table, $object);
    }

    /**
     * Build object from json data
     * @param $table OrmTable
     * @param $data array[id=1, name='Serg', birthdate='1986-02-21']
     * @return array[0=>OrmPersistenceBase, 1=>errors[]]
     */
    public static function buildObject($table, $data) {
        return OrmUtils::buildObject($table, $data);
    }

    public static function createTable (OrmTable $table) {
        OrmRegister::createTable($table);
    }

    /**
     * Get table object using it's name
     * @param $tableName
     * @return OrmTable
     */
    public static function getTable($tableName) {
        return OrmRegister::getTable($tableName, ORM::$registeredTables);
    }

    public static function registerTablesChain($tableName) {
        OrmRegister::registerTablesChain($tableName, ORM::$registeredTables);
    }

    /**
     * @param $tableName string
     * @return OrmTable
     * @throws Exception in case, when table can't be founded
     */
    public static function registerTable($tableName) {
        return OrmRegister::registerTable($tableName, ORM::$registeredTables);
    }

    /**
     * Register table in runtime.
     * Required on site initialization
     * @param OrmTable $table
     * @throws FwException
     */
    public static function registerTableOnFly (OrmTable $table) {
        OrmRegister::registerTableOnFly($table, ORM::$registeredTables);
    }
}